### ISSUE TITLE
Include new Windows libraries from NodeWebkit v. 0.11.5

### ISSUE THREAD

**Issue by Fiorenza-Oppici** [mllrsohn/node-webkit-builder#146]
Latest Nw version ships files pdf.dll and d3dcompiler_46.dll, the builder doesn't still include those.

**Comment by joshuaterrill** [comment]
I've just made a pull request. https://github.com/mllrsohn/node-webkit-builder/pull/238

**Comment by freakinside** [comment]
Included on #220 pull request.

**Comment by adam-lynch** [comment]
Released
