### ISSUE TITLE
Utils.js: function copyFile always prints "chmod <perms> on <file> failed after copying, ignoring".

### ISSUE THREAD

**Issue by bambooCZ** [mllrsohn/node-webkit-builder#147]
solution is to check if there actually was an error, ex. 

```Javascript
if (err) {
    _event.emit('log', 'chmod ' + stats.mode + ' on ' + dest + ' failed after copying, ignoring');
}
```

**Comment by bambooCZ** [comment]
also mentioned in #141

**Comment by bambooCZ** [comment]
Actualy, whole copy file method is pretty fucked up...

**Comment by mdb** [comment]
Is there a planned release now that this issue is closed? My team's CI environment relies upon an npm release.

Apologies for nagging ;)

Thanks for the fix!

**Comment by adam-lynch** [comment]
Yeah, sometime today (Irish time).

**Comment by mdb** [comment]
@adam-lynch Great - thanks so much.

**Comment by adam-lynch** [comment]
`1.0.8` published.
