### ISSUE TITLE
Is this supposed to create an app for Macs?

### ISSUE THREAD

**Issue by zwhitchcox** [mllrsohn/node-webkit-builder#152]
I'm looking for a tool that can turn my node-webkit app into a regular app for mac that other people can use. Does this program do that? I looked through the readme, but couldn't find anywhere that shows you how to do that. Is this the right program for something like that?

**Comment by adam-lynch** [comment]
The readme needs some work. The `build` method will create a `.app` for you. `run` is used during dev (which I personally don't use). Both take the same options pretty much.

Seethe first example hre: https://github.com/mllrsohn/node-webkit-builder#run-node-webkit. That'll build an executable for you.

**Comment by zwhitchcox** [comment]
You'll have to forgive me...I'm fairly new to node wk, but I've created an app, and that's totally done. It does exactly what I want it to do.

But in terms of getting it to work, I just take that code that's in the README and put it in a file say called 'build.js', then (after installing node-webkit-builder), I just say 
```Shell
node builder.js
```

Because I did that, and it said 'No files matching'.

Sorry to be such a pain; I'm sure everyone else gets this easily.

**Comment by adam-lynch** [comment]
No prob.

See this section of the example:

```javascript
var nw = new NwBuilder({
    files: './path/to/nwfiles/**/**', // use the glob format
    platforms: ['osx32', 'osx64', 'win32', 'win64']
});
```

You need to change the `files` property. This value should be a [glob](https://github.com/jedmao/simple-glob#globbing-patterns).

Let's say you have a `src` directory which contains all your files;

>
- build.js
- src/
   - package.json
   - index.html
   - etc

Then your `files` property should contain `./src/**`.

Also, switch the `platforms` property's value to just `['osx32']`.

**Comment by zwhitchcox** [comment]
Wow, it seems so obvious now. Thank you so much!

**Comment by adam-lynch** [comment]
No problem :+1:. If you ever find anything wrong with the readme, etc. don't be afraid to create an issue / pull-request :smile:.
