### ISSUE TITLE
Trying to download the wrong platform of node webkit when given -v 0.8.6 -p ['win32'] under command line

### ISSUE THREAD

**Issue by yuchuan1** [mllrsohn/node-webkit-builder#154]
After executing the following command running from windows 8.1 64bit

    nwbuild -v 0.8.6 -p ['win32']  -r app

I get this error

    Downloading: http://dl.node-webkit.org/v0.8.6/node-webkit-v0.8.6-win-x64.zip
    ERROR: The version 0.8.6 does not have a corresponding build posted at http://dl.node-webkit.org/. Please choose a version from that list.Unable to download nodewebkit.

**Comment by cbabos** [comment]
@yuchuan1 
In run mode, the nwbuild will download the binary for the *current* platform. 
From the source the `-r` param is run mode, which has the description: `Runs node-webkit for the current platform`

**Comment by yuchuan1** [comment]
@cbabos  
Thank for the quick reply, I thought -p option would overwrite that.
Closing the issue now.
