### ISSUE TITLE
New node-webkit announcement regarding name change and move to io.js

### ISSUE THREAD

**Issue by tphalp** [mllrsohn/node-webkit-builder#157]
Roger announced today that they are changing the name of node-webkit to NW.js, and moving to io.js

https://groups.google.com/forum/#!topic/nwjs-general/V1FhvfaFIzQ

~~Not sure why, but when I click on the link, it gives a 404, but if I copy and paste it into a browser, it works. If someone can fix that, please do.~~

Seems to work now...

**Comment by trevorah** [comment]
#156 should fix the existing downloads, but we need some changes to deal with v0.12.0's filename changes.

**Comment by tphalp** [comment]
Awesome, thanks.
