### ISSUE TITLE
consider to support compile the files with nwsnapshot?

### ISSUE THREAD

**Issue by lisposter** [mllrsohn/node-webkit-builder#162]
I think this will protect app's code more security.

https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot

**Comment by adam-lynch** [comment]
I don't know does anyone use this. The wiki entry says itself it would make your app about 30% slower and you can't use self-executing anonymous functions or write closures like that so that means most people's code would break and you couldn't use jQuery, etc. Correct me if I'm wrong.

**Comment by lisposter** [comment]
seems you're right, anyway just mention it.

**Comment by adam-lynch** [comment]
Thanks
