### ISSUE TITLE
Creating windows build is missing the small application icon in the upper left of application window

### ISSUE THREAD

**Issue by twickstrom** [mllrsohn/node-webkit-builder#165]
I am building this from mac OSX 10.10.1

Also during the build it is throwing the following error:
fixme:wincodecs:PngDecoder_Block_GetCount 0x1424858,0x32f55c: stub

I believe this is from Wine, which I installed with homebrew version 1.6.2.

The ico file includes the following sizes: 256, 180, 128, 96, 72, 64, 48, 32, 24, 20, 16.

I attached a screenshot to show the Icon that is missing. Any help would be appreciated!

![windows-missing-icon](https://cloud.githubusercontent.com/assets/775346/5823681/71bd7e2c-a0a4-11e4-8ee3-6bdc8e364775.png)

**Comment by avihaymenahem** [comment]
Its a known bug in nw:
https://github.com/nwjs/nw.js/wiki/Icons

**Comment by twickstrom** [comment]
Thank you sir! Sorry I missed that and thanks for pointing me in the right direction!

**Comment by avihaymenahem** [comment]
You welcome! (you can close the issue on the bottom)
