### ISSUE TITLE
Mac OSX custom about file.

### ISSUE THREAD

**Issue by twickstrom** [mllrsohn/node-webkit-builder#166]
When adding a custom credits file to be displayed when you click App -> About requires 2 click for it to display.

Also the version does not populate.

Any help would be appreciated.

**Comment by 6** [comment]
I'm having the same problems with the About Panel & version.

**Comment by 6** [comment]
never mind, seems to be fixed by: https://github.com/mllrsohn/node-webkit-builder/pull/155

**Comment by trevorah** [comment]
v1.0.7 should be live now with the fix. Have fun with your about panels you two!

**Comment by twickstrom** [comment]
Nice work!

**Comment by 6** [comment]
thanks!
