### ISSUE TITLE
Support npm-based NW.js installs

### ISSUE THREAD

**Issue by matthew-dean** [mllrsohn/node-webkit-builder#167]
Instead of having to manually configure the version for binaries, it would be nice of node-webkit-builder detected and supported the version of the newer npm installs, which will put the nw binary in the local project folder.

https://www.npmjs.com/package/nw

**Comment by adam-lynch** [comment]
We can't keep let it update to the newer version automatically. nwjs have had breaking changes in the past. We are thinking of re-writing this so maybe (npm) nwjs and this module can share the same version cache so you don't need to download it twice.

**Comment by adam-lynch** [comment]
Re-reading this... you know the default value for [`options.version`](https://github.com/mllrsohn/node-webkit-builder#optionsversion) is `latest` right? Just in case I'm reading your original comment wrongly.

**Comment by matthew-dean** [comment]
What I actually meant was that since nwjs had introduced a new (secondary) packaging / distribution method, I wondered if node-webkit-builder was going to support that new method, that's all. But good to know about the version property. So, ommitting it will default to latest?

**Comment by adam-lynch** [comment]
Yeah, should do :+1:. We're also thinking about dropping node-webkit-builder.run and suggesting people to use the nw-installer instead, but we're not sure.
