### ISSUE TITLE
Defer winIco failure on builds

### ISSUE THREAD

**Issue by shennan** [mllrsohn/node-webkit-builder#175]
```
Error while updating the Windows icon. Wine (winehq.org) must be installed to add custom icons from Mac and Linux.
````

I think we should relegate this error to a warning and allow the build to continue without the icon. We're forcing a dependency on Wine which OSX users might want to ignore in development, but keep the `winIco` option within the script for posterity and use by others.

**Comment by hermwong** [comment]
I'm receiving this error as well when using `grunt-node-webkit-builder` v1.0.0 which uses `node-webkit-builder` v1.0.8.

**Comment by adam-lynch** [comment]
@shennan shouldn't Mac users just not build for Windows at all in dev?

**Comment by shennan** [comment]
@adam-lynch Possibly - but this is an even better reason for downgrading it to a warning. Many will be using this module in a build stack, not necessarily as a first class module via the command line. If there is code like this within that stack:
```
new NwBuilder({
    files: 'path/to/files/**',
    platforms: ['win32', 'win64', 'osx32', 'osx64'],
    buildDir: 'path/to/build',
    cacheDir: 'path/to/cache',
    macIcns: 'path/to/macIcon.icns',
    winIco: 'path/to/winIcon.ico'
});
```
Then it requires an extra configuration step to determine the platform, mitigate the windows values and  ensure that every application that *can* be built, *will* be built.

If a Wine process fails, throw an error. But throwing an error when checking on an optional configuration seems unfair in my opinion.

**Comment by felicienfrancois** [comment]
This is maybe an optional configuration but it is critical in a release process (releasing an app without its icon .... is critical for me and for most people).
Additionally there is no reason for building for all platforms in dev (use run instead).

Anyway, If you don't want this behavior, you can split the build in several sequential steps:
```
new NwBuilder({
    ...
    platforms: ['osx32', 'osx64'],
    ...
});
new NwBuilder({
    ...
    platforms: ['win32', 'win64'],
    ...
});
```
and same with the grunt plugin.
In the opposite case (if there is no fail and just a warning), there is no possible workaround for people that want build to fail

**Comment by adam-lynch** [comment]
@shennan I get what you're saying but this might be out of scope for this module. 

If it was me, I already know in my build whether or not it's for dev / production. If it's dev, I'd just add the current platform to `platforms`, if it's production I'd add all of them (or the subset you want in production).

FYI, this module will be moving away from being a dev tool for *running* your app and solely just for building executables for production; see #98.

**Comment by hermwong** [comment]
I'm actually using `node-webkit-builder` to build the release binaries (Mac & Windows) using my Mac notebook.

Would definitely like to see winIco supported in the newest version of the `node-webkit-builder` when it's run on Mac so that I don't have to set up my build environment on a Windows notebook.

**Comment by felicienfrancois** [comment]
@hermwong it is already supported but it requires wine to be installed:
```
brew install wine
```

**Comment by hermwong** [comment]
@felicienfrancois, I already have `wine` installed. I'm able to build when using `node-webkit-builder 0.2.2` and `node-webkit 0.10.5`, however if I want to update to newer version of `node-webkit 0.11.X`, it requires me to update to `node-webkit-builder 1.0.8` which then throws the error mentioned in this issue even though I already have `wine` installed.

**Comment by felicienfrancois** [comment]
@hermwong OK, so the issue you're facing is not related to the current one. You should creates a new issue (after checking that `wine` is available from command line on your computer).

**Comment by hermwong** [comment]
@felicienfrancois, the issue is that when I'm attempting to build my project with using `node-webkit-builder 1.0.8` it fails on the `winIco` property and the error message says that I require `wine` to be installed (even though I already have it installed).

If I change my project to use `node-webkit-builder 0.2.3` it works perfectly.

**Comment by shennan** [comment]
@hermwong Please create a new issue with this if you're still having problems.

@felicienfrancois I see your point but in my opinion 90% of node-webkit builds are development builds to test functionality of the application. Getting Wine running on OSX was a drag, but colleagues using Windows were still able to build with the exact same `NWBuilder` configuration, which was enough for my use-case.

I'll back down on this issue - for now!

:-)
