### ISSUE TITLE
Issue in using node-webkit-builder

### ISSUE THREAD

**Issue by nidhin001** [mllrsohn/node-webkit-builder#177]
Hi, I'm confused about how to use node webkit builder. I installed builder using  "npm install node-webkit-builder --save-dev" and when I run "nwbuild -r path/to/your/younwapp/" in my project directory I got the error "bash: nwbuild: command not found" . What is the correct way to use nw-builder to package the app. ?

**Comment by mattstyles** [comment]
if you want to use it like that then install globally

`npm i -g node-webkit-builder`

Although some people are currently having problems with the shebang in the nwbuild. Another way is to ensure that node runs it properly, from your current install location:

`node ./node_modules/node-webkit-builder/bin/nwbuild -r path/to/nwapp`

Or, follow instructions in the readme to do it programmatically.

**Comment by adam-lynch** [comment]
Thanks @mattstyles

**Comment by 1j01** [comment]
You can use the CLI from the scripts field in your package.json when it's saved as a dependecy
