### ISSUE TITLE
1.0.8 release not tagged

### ISSUE THREAD

**Issue by shnist** [mllrsohn/node-webkit-builder#178]
Hi,

I've noticed that the package.json file has been updated to 1.0.8, but there is no tag and the release notes have not been updated. Is this intentional? Should we not use 1.0.8 for now?

Thanks

**Comment by trevorah** [comment]
Whoops, I've just added the missing tag. Thanks for pointing that out @shnist. Eagle eyes!

1.0.8 is [live on npm](https://www.npmjs.com/package/node-webkit-builder), so you can use it.

**Comment by shnist** [comment]
Thanks @trevorah! Would it be possible to update the release notes as well when you have time? Cheers

**Comment by trevorah** [comment]
Sure. They should be up to date now.
