### ISSUE TITLE
winIco doesn't appear to be changing the .exe icon

### ISSUE THREAD

**Issue by jminnick** [mllrsohn/node-webkit-builder#183]
I'm building on a windows 8 box. When I explore my .exe using winresourcer, I see that it has both the default nw.ico and the .ico I am trying to replace it with.  Seems it should be replacing the default. My custom .ico is second in the list and the nw.ico is first.

![image](https://cloud.githubusercontent.com/assets/3810135/6072726/e841184e-ad72-11e4-9eb9-628f7a38ec3f.png)

When I browse to the directory to where the .exe is, I still see the default nw.ico.

**Comment by jminnick** [comment]
Figured this out. Either our .ico was too large or Windows just didn't like the format. Also, make sure when an ico changes, your PC is restarted to see the changes. Windows caches the .ico files.

**Comment by adam-lynch** [comment]
[This](https://gist.github.com/adam-lynch/e626cc9aaba784f9199e) may or may not help in the future
