### ISSUE TITLE
[Feature] Allow disabling executable+zip concatenation

### ISSUE THREAD

**Issue by kohenkatz** [mllrsohn/node-webkit-builder#186]
Currently, the builder will always merge the zipped `app.nw` file into the NW.js executable (except for Mac OS, where that can be disabled.)

Another option that NW.js allows is leaving the zipped application alongside the executable with the name `package.nw`.

I think there should be an option for whether to concatenate or not, something like this (based on `options.macZip`):

> #### options.concatenate
>
> Type: `Boolean`
> Default value: `true`
>
> Concatenate the application `ZIP` file with the NW.js executable for each platform.  If this option is disabled, the zipped application code will be renamed `package.nw` and placed in the folder alongside the NW.js executable.

I am willing to do a Pull Request for this, but I wanted to make sure there is interest in accepting it before I do the work.

**Comment by adam-lynch** [comment]
Closing in favour of #164
