### ISSUE TITLE
Broken on Mac because of \r instead of \n

### ISSUE THREAD

**Issue by adius** [mllrsohn/node-webkit-builder#188]
You're using the carriage return character (used on windows) and not the newline character for line breaks. => It's broken on mac and linux.

```
$ nwbuild -r ./app

env: node\r: No such file or directory
```

**Comment by konsumer** [comment]
+1

**Comment by felicienfrancois** [comment]
Seems to be a reccuring issue: #75, #108, #109

You can fix it by removing all `\r` in node-webkit-builder files. You can do it with most code editors, including vim with the following command ` :set ff=unix`.

If you've time to, you can make a pull request.

**Comment by felicienfrancois** [comment]
Also note that windows uses `\r\n` and not `\r alone`. So `\r` should be removed and not replaced.

`\r alone` was used by old Mac OSX (before it comes to a BSD fork)

**Comment by konsumer** [comment]
I tried to make a PR, but it didn't register just /n changes. WIll need to investigate when I have a minute.

**Comment by adam-lynch** [comment]
Would love a PR to fix this. Maybe a build step to normalize line-endings would be the best solution. Maybe https://github.com/ryanve/eol would help, I don't know.

**Comment by konsumer** [comment]
This would fix it once, as just doing it in your editor, but it still won't register in git. see [this](https://help.github.com/articles/dealing-with-line-endings/) for a fix.  I will try to make a PR for it, now.

**Comment by konsumer** [comment]
actually, it looks like you already have that. hmm.

**Comment by konsumer** [comment]
And `./bin/nwbuild` works, so maybe just `npm publish`?

**Comment by adam-lynch** [comment]
@konsumer 99.9999% sure I did that ("Dealing with line endings") before to fix this and it did nothing. 

---

>And ./bin/nwbuild works, so maybe just npm publish?

I'm not following you.

**Comment by konsumer** [comment]
Yep, that is my comment above. Just made build script to fix line-endings & publish to npm. I think maybe npm doesn't fix line-endings like git does.

**Comment by konsumer** [comment]
What I am saying is that my actual checkout is fine (I can run `./bin/nwbuild`, which is what your package.json links to in `bin`) so it's something other than `.gitattributes` file, which you already made. To fix this, regardless of whether it's an issue with how npm packages files, I made a nice build script for you :)

**Comment by adam-lynch** [comment]
Fixed in 1.0.9.
