### ISSUE TITLE
nwbuild returning "No Files Matching"

### ISSUE THREAD

**Issue by skadimoolam** [mllrsohn/node-webkit-builder#190]
My Dev Environment details,
OS: Win7
Node: 0.12.0
NPM: 2.5.1

I try to run `nwbuild --run C:\Users\Admin\Dropbox\Web Dev\Polymer\tes\` and  `node C:/Users/Admin/AppData/Roaming/npm/node_modules/node-webkit-builder/bin/nwbuild -r C:/Users/Admin/Dropbox/Web Dev/Polymer/tes/` commands and nwbuild returns "No Files Matching", but it used to work before.

I think it's something to do with the latest Node update cause I have had this problem only since the update.
It would be great if you guys could find and resolve the problem.

**Comment by adam-lynch** [comment]
Going to ask something that might be obvious... Did you try wrapping your path in double-quotes? (There's a space in it)

**Comment by skadimoolam** [comment]
Thank you adam-lynch, wrapping the Path with Quotes were the problem, but I have no idea how it worked previously.
