### ISSUE TITLE
Possible to specify NODE_ENV?

### ISSUE THREAD

**Issue by marbemac** [mllrsohn/node-webkit-builder#194]
Is it possible to tell node-webkit (or node-webkit-builder) to use NODE_ENV=production when running the app? Maybe this is more of a node-webkit question, I'm not sure.

**Comment by adam-lynch** [comment]
I think this is more of a node-webkit question. I personally don't know really what you need to do. If you find out how to do it and node-webkit-builder blocks that, then let us know :smile:.
