### ISSUE TITLE
io.js support?

### ISSUE THREAD

**Issue by marbemac** [mllrsohn/node-webkit-builder#197]
Hi, everything works OK in node 0.12, but in io.js 1.3 I get the error below. Looks like for some reason mdl in proxyquire is read-only. Does anybody have this working in io.js or is there an alternative to proxyquire?

I asked the same question on proxyquire here but no love so far: https://github.com/thlorenz/proxyquire/issues/51

The error occurs here: https://github.com/thlorenz/proxyquire/blob/master/lib/proxyquire.js#L15
```js
if (!mdl[key])  mdl[key] = original[key];
                               ^
TypeError: Cannot assign to read only property 'F_OK' of #<Object>
```

**Comment by nyagi** [comment]
Same issue.

**Comment by brian-mann** [comment]
Same here.

**Comment by bastimeyer** [comment]
See my PR over there at https://github.com/thlorenz/proxyquire/pull/52

@adam-lynch 
If this gets merged, you need to update the `proxyquire` dependency versions of `graceful-ncp` and `graceful-fs-extra` to make this work here, too. It's set to `~1.0.1` right now, the latest version already is `1.3.1`.

**Comment by adam-lynch** [comment]
Thanks.

**Comment by bastimeyer** [comment]
proxyquire `1.3.2` has just been pushed to npm...

**Comment by bastimeyer** [comment]
@adam-lynch could you please update the dependencies then? :grinning:

**Comment by adam-lynch** [comment]
@bastimeyer will do today :)

**Comment by adam-lynch** [comment]
`1.1.0` published

**Comment by marbemac** [comment]
@adam-lynch @bastimeyer Awesome thanks guys!

**Comment by bastimeyer** [comment]
@adam-lynch  thx.. also pls don't forget to bump the dependency version inside the grunt repo too... otherwise **graceful-ncp@0.0.1** will be resolved:
```
grunt-node-webkit-builder@1.0.0 node_modules/grunt-node-webkit-builder
└── node-webkit-builder@1.0.10 (platform-overrides@1.0.1, inherits@2.0.1, progress@1.1.8, rcedit@0.2.0, temp@0.7.0, semver@2.3.2, optimist@0.6.1, simple-glob@0.1.0, rimraf@2.3.1, graceful-fs-extra@1.0.4, graceful-ncp@0.0.1, tar-fs@0.3.3, bluebird@1.2.4, request@2.40.0, winresourcer@0.9.0, lodash@2.4.1, decompress-zip@0.0.8, archiver@0.13.1, update-notifier@0.1.10, plist@1.1.0)
```

**Comment by adam-lynch** [comment]
@bastimeyer won't it just work? (https://nodesource.com/blog/semver-tilde-and-caret). Correct me if I'm wrong. Or maybe you just mean I should bust the cache.

**Comment by bastimeyer** [comment]
> ~1.2.3 matches all 1.2.x versions but misses 1.3.0
> ^1.2.3 matches any 1.x.x release including 1.3.0

https://github.com/mllrsohn/grunt-node-webkit-builder/blob/3ad75999669409c7d01a6396a2747b5963fdca18/package.json#L36

current version is 1.1.0 though

**Comment by adam-lynch** [comment]
Thanks. Just published a new grunt version.


Regards,
Adam Lynch

**Comment by bastimeyer** [comment]
Cool, thanks :+1:
