### ISSUE TITLE
Latest version (1.0.10) destroys my files and quits with ENOENT error

### ISSUE THREAD

**Issue by ChristianWeyer** [mllrsohn/node-webkit-builder#198]
Hm... I tried to run nwbuild against my code folder.
After several files successfully processed I get this error:

Error: ENOENT, open '/Users/foo/www/app/app.js']
    errno: -2,
    code: 'ENOENT',
    path: '/Users/foo/www/app/app.js' 

And all my files have been destroyed and are now 0 bytes :/
This was tested on MacOSX 10.10.2.

Thanks.

**Comment by ChristianWeyer** [comment]
Does anybody have any ideas what could be the issue?

**Comment by ChristianWeyer** [comment]
@adam-lynch this actually happens on various projects here - strange...

**Comment by adam-lynch** [comment]
What do you mean by "destroys your files"? Could you show me the way you're using node-webkit-builder (& the config)?

**Comment by ChristianWeyer** [comment]
Sure :)

For demo sake, use the AngularJS Material Start project and git clone it: https://github.com/angular/material-start

Install npm install node-webkit-builder

Then use this command:
$ node_modules/.bin/nwbuild -p osx64 app

After that I get an error:
[ { [Error: ENOENT, open '/Users/christianweyer/GitHub/material-start/client/bower_components/angular-aria/angular-aria.min.js']
    errno: -2,
    code: 'ENOENT',
    path: '/Users/christianweyer/GitHub/material-start/app/bower_components/angular-aria/angular-aria.min.js' } ]

Looking at the files, they are all either deleted or 0 bytes in size :/

**Comment by ChristianWeyer** [comment]
@adam-lynch do you need more information?

**Comment by adam-lynch** [comment]
~~@ChristianWeyer to be honest, I'm totally swamped. It's 9PM my time, I've loads to do and I'm flying out of the country tomorrow. I'll try my best though to get to it though! In the meantime, try `1.1.0` just in case that has somehow fixed this.~~

I just did it on my Windows 8.1 machine (with `1.1.0`) and it worked. I did have to add a `package.json` in `app` though. What's in your `app/package.json`?

**Comment by ChristianWeyer** [comment]
You efforts are much appreciated!

This is my package.json:
{
  "name": "TT Contacts",
  "description": "Simple contacts applicationp",
  "version": "0.1.0",
  "main": "index.html",
  "window": {
    "title": "TT Contacts",
    "toolbar": false,
    "frame": true,
    "position": "mouse",
    "width": 1024,
    "height": 720
  }
}

**Comment by adam-lynch** [comment]
Try without a space in the `name` field?

**Comment by ChristianWeyer** [comment]
With 1.1.0 everything works as expected - no matter I have a space or not in the name ;)
Thanks!

**Comment by adam-lynch** [comment]
Great!
