### ISSUE TITLE
--macIcns doesn't alter Info.plist

### ISSUE THREAD

**Issue by oskarrough** [mllrsohn/node-webkit-builder#208]
Hi, I'm having trouble adding an icon to my osx builds. The following commands aren't changing anything in Info.plist, which leaves the default nw.icns.

`$ nwbuild dist -p 'osx64' --macIcns app.nw/my-icon.icns'`

What am I missing? Changing `CFBundleIconFile` manually in the plist works fine. I'm using node-webkit-builder v1.0.8.

**Comment by praves77** [comment]
I've fixed my fork for --macIcns and --winIco. You can pull it from here : https://github.com/praves77/node-webkit-builder/commit/452a3c91692b234c16e7ca1196ec11dedb867599

**Comment by adam-lynch** [comment]
Fixed by #224

**Comment by adam-lynch** [comment]
`1.0.12` published
