### ISSUE TITLE
How can I build without packing files?

### ISSUE THREAD

**Issue by zsxsoft** [mllrsohn/node-webkit-builder#223]
I want to provide a ``config.js`` to customize, so I don't need to pack my codes into a zip file.. But I found that I can't build an empty ``nw``.. 
```javascript
    if(!this.options.files) {
        throw new Error('Please specify some files');
    }
```
If I only add ``package.json`` to ``options.files``, generated ``nw`` will not load ``package.json`` in the same directory but load itself carried.

I will not modify the source code in ``node_modules`` because I want to maintain the compatibility if you updated. But how can I do that?

**Comment by adam-lynch** [comment]
You want to build an app without `files`?

**Comment by zsxsoft** [comment]
Yes. I will copy files manually.

**Comment by adam-lynch** [comment]
I'm sorry, I'm not sure exactly what you want to do. As far as I remember, this module using `files` to find the `package.json`. What do you mean when you `but load itself carried`?

**Comment by zsxsoft** [comment]
Sorry.. Close it.
