### ISSUE TITLE
Download of nw fails with "Invalid protocol: undefined"

### ISSUE THREAD

**Issue by stuartlangridge** [mllrsohn/node-webkit-builder#226]
When running nwb (as part of phonegap-app-desktop build), it dies with "Fatal error: Unable to download nodewebkit." After some debugging, the error being thrown is from request, and is "Invalid protocol: undefined", in the downloader. This is because `lib/downloader.js` line 50 sets `rq.proxy = true`, but the [request docs](https://github.com/request/request#proxies) show that `request.proxy` should be set to a proxy URL, not a boolean. I commented out `rq.proxy=true` and that made everything work, but haven't sent a pull request removing the line because I imagine you set proxy=true for some reason and so this needs thinking through.

**Comment by adam-lynch** [comment]
Thanks @stuartlangridge. Hmm, not sure about that line.

**Comment by adam-lynch** [comment]
Closing this in favour of #222
