### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by dottodot** [mllrsohn/node-webkit-builder#229]
If I build my app using the command line i.e. ```nwbuild -r -v 0.12.2 hosts/myapp``` it works fine but when I package it using..

```
var nw = new NwBuilder({
    version: '0.12.2',
    files: [ './**'],
    platforms: ['osx64'],
    buildDir: '../myapp/build',
    cacheDir: '../myapp/cache'
  });
```
i get error during the build progress and when I open the app it doesn't work and all I get is the error ```require is not defined``` in the console.log

The error i'm getting is

```
[09:01:48] node-webkit-builder [ { [Error: EINVAL, readlink '/myapp/build/myapp/osx64/myapp.app/Contents/Resources/app.nw/node_modules/include-all']
    errno: 18,
    code: 'EINVAL',
    path: '/myapp/build/myapp/osx64/myapp.app/Contents/Resources/app.nw/node_modules/include-all' } ]
```

Not sure what I doing wrong that's preventing me package it.

**Comment by adam-lynch** [comment]
Does it work without `node-webkit-builder`?

**Comment by dottodot** [comment]
Do you mean does it work as a regular nodejs app? If so yes. Or do if mean if a package it without node-webkit-builder?

**Comment by adam-lynch** [comment]
Without node-webkit-builder. If you run it with [`nw`](http://npmjs.org/package/nw) for example.

**Comment by dottodot** [comment]
I think it something to do with being a sailsjs app so going to scrap using it for this as it's probably a bit too over the top anyway.

**Comment by adam-lynch** [comment]
Ok cool, close this if this issue is resolved :+1:
