### ISSUE TITLE
Cannot run nodewebkit 0.8.6 under win64

### ISSUE THREAD

**Issue by uksus70** [mllrsohn/node-webkit-builder#234]
Trying:
`nwbuild -v 0.8.6 -r src/app/`

Getting:
```
Downloading: http://dl.nwjs.io/v0.8.6/node-webkit-v0.8.6-win-x64.zip
ERROR: The version 0.8.6 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.
Unable to download nodewebkit.
```

Indeed, http://dl.nwjs.io/v0.8.6/ contains only win32 build.
```
[DIR]	Parent Directory	 	-	 
[   ]	node-webkit-v0.8.6-linux-ia32.tar.gz	16-Apr-2014 08:42	36M	 
[   ]	node-webkit-v0.8.6-linux-x64.tar.gz	16-Apr-2014 08:44	38M	 
[   ]	node-webkit-v0.8.6-osx-ia32.zip	16-Apr-2014 01:47	34M	 
[   ]	node-webkit-v0.8.6-win-ia32.zip	16-Apr-2014 05:49	25M	 
```

Can I specify win32 as a platform for running? `nwbuild -v 0.8.6 -p win32 -r src/app/` is not working.

node-webkit-builder version is 1.0.12.

**Comment by adam-lynch** [comment]
Ah... sorry, my mistake. I added a check to see if the 64-bit Windows is there just to validate that it's not an alpha build. Will sort ASAP.

**Comment by adam-lynch** [comment]
nw-builder@2.0.1 published
