### ISSUE TITLE
How to confirm build success?

### ISSUE THREAD

**Issue by pebanfield** [mllrsohn/node-webkit-builder#237]
Hi - This is not exactly an issue. It's possible that I'm simply confused so apologies in advance. 

After running the gulp task a build directory appears at the project root and so seems to have successfully generated release builds. However, when I look in the build resources directory I don't see any files from my app. Is this the expected behavior? 

For example, in build/myApp/osx64/myApp.app/Contents/Resources I do not see my app resources. I don't see an app.nw file anywhere either. My expectation was that the contents of the files specified in NwBuilder options would end up in the build somewhere, but maybe I'm not understanding the point? Is there another packaging step? Where can I expect to see my app files? 

Thanks!

Peter

**Comment by adam-lynch** [comment]
Hey @pebanfield... yeah, there's something up. Could you show me exactly how you're calling node-webkit-builder and what your project structure is like?

**Comment by pebanfield** [comment]
Hi Adam - Yes sure can. You can try this yeoman generator if you are on Mac - 

npm install -g generator-nwjs-nodegit
mkdir myTest && cd myTest && yo nwjs-nodegit
alias nw="/Applications/nwjs.app/Contents/MacOS/nwjs"
nw nwapp

This should load a sample based on your node-webkit-builder example. The generator project is here - 

https://github.com/pebanfield/generator-nwjs-nodegit

**Comment by pebanfield** [comment]
Thanks!

**Comment by adam-lynch** [comment]
Are your files inside the `nwapp` directory?

**Comment by pebanfield** [comment]
Yes. But this is a generator project so they aren't there until you install. Maybe it's easier to look at this project - 

https://github.com/pebanfield/change-viewer

**Comment by pebanfield** [comment]
Oh hay I want to Cork once and had a look around. Cool town.

**Comment by adam-lynch** [comment]
Nice :grinning:.

So you run `gulp` and it doesn't work? Could you try changing this line https://github.com/pebanfield/change-viewer/blob/master/Gulpfile.js#L9 to have `./nwapp/**/*` instead?

**Comment by pebanfield** [comment]
Ah k so it was the icons directory that was stopping the build. My bad. I guess I didn't have it in the right place and shouldn't have ignored the error. Thanks!

**Comment by pebanfield** [comment]
Anyways it is functioning properly now.

**Comment by adam-lynch** [comment]
Great
