### ISSUE TITLE
Getting error: "The application cannot be opened because its executable is missing." when trying to open the app.

### ISSUE THREAD

**Issue by jilldenae** [mllrsohn/node-webkit-builder#58]
After building my app, the Windows version works fine, but when I try to open the osx version (using open appName.app in terminal), I get "The application cannot be opened because its executable is missing."

I've looked at the Info.plist file, and it lists node-webkit as the executable.  I found that file in appName.app/Contents/MacOS.  Tried changing Info.plist to specify that path, but that didn't help.  

Any ideas?  Thank you very much for your help.  
--
Built via terminal on Mac, using "sudo nwbuild -p osx app.nw" (my app is in the app.nw directory).

**Comment by Kilowhisky** [comment]
Any resolution on this? I'm having this same issue. 

My build file looks like this.

```
    name: 'myApp',
    appName: 'myApp',
    version: '0.12.2',
    platforms: ['osx'],
    files: ['package.json','dist/favicon_16x16.png','dist/nwjs/node-main.js','dist/nwjs/build.json'],
    winIco: 'dist/favicon.ico',
    macIcns: 'dist/favicon.icns',
    buildType: function() {
        return this.appVersion;
    }
```
